#!/usr/bin/env python3
"""Generate Coder workspace preset blocks from the profile store.

Emits Terraform `data "coder_workspace_preset"` blocks -- one per profile that
has both a built Odoo image AND a successful mask run (so it has a masked dump
to hydrate from). Written to coder/templates/odoo-synth-env/presets.tf, which
`coder templates push` picks up automatically.

A profile becomes a one-click "Create workspace" preset in the Coder dashboard,
carrying its image, dump, git token secret, repo, and discovery-derived
odoo.conf extras -- everything the panel used to pass. Adding a new repo+DB is
now: build + mask it (via the CLI), then re-run `deploy/12_publish_template.sh`.

Usage: python3 deploy/_gen_presets.py [profile_db_path]
"""
from __future__ import annotations
import base64
import json
import sqlite3
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "coder" / "templates" / "odoo-synth-env" / "presets.tf"
DEFAULT_INSTANCE = "t3.large"


def _hcl_string(s: str) -> str:
    """Escape a string for an HCL quoted literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    db = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        REPO / "controlpanel" / "backend" / "controlpanel.db")
    if not db.exists():
        sys.stderr.write(f"WARN: profile db not found at {db}; writing no presets\n")
        OUT.write_text('# No profile store found; no presets generated.\n')
        return 0

    conn = sqlite3.connect(str(db))
    conn.row_factory = sqlite3.Row
    # profiles with a built image
    profs = conn.execute(
        "SELECT id, label, description, image_uri, odoo_conf_extra, "
        "git_token_secret, addons_git_url, addons_git_ref "
        "FROM profiles WHERE image_uri IS NOT NULL AND image_status IN ('built','ready','discovered')"
    ).fetchall()

    blocks: list[str] = []
    seen = 0
    for p in profs:
        # latest successful mask run -> masked dump uri
        row = conn.execute(
            "SELECT result FROM runs WHERE profile_id=? AND status='succeeded' "
            "AND result LIKE '%masked_dump_s3_uri%' "
            "ORDER BY created_at DESC LIMIT 1", (p["id"],)).fetchone()
        if not row:
            continue  # no dump yet -> not preset-worthy
        try:
            res = json.loads(row["result"])
        except Exception:
            continue
        dump_uri = res.get("masked_dump_s3_uri")
        if not dump_uri:
            continue
        conf_extra = p["odoo_conf_extra"] or ""
        conf_b64 = base64.b64encode(conf_extra.encode()).decode()
        label = (p["label"] or p["id"]).strip() or p["id"]
        desc = (p["description"] or f"Profile {p['id']}").strip()
        repo_url = p["addons_git_url"] or ""
        repo_branch = p["addons_git_ref"] or ""
        git_tok = p["git_token_secret"] or ""
        seen += 1
        blocks.append(f'''# Preset for profile {p["id"]} (auto-generated by deploy/_gen_presets.py)
data "coder_workspace_preset" "profile_{p["id"].replace("-","_").replace(".","_")}" {{
  default     = {"true" if seen == 1 else "false"}
  name        = "{_hcl_string(label)}"
  description = "{_hcl_string(desc)}"
  parameters = {{
    odoo_image           = "{_hcl_string(p["image_uri"])}"
    dump_s3_uri          = "{_hcl_string(dump_uri)}"
    git_token_secret     = "{_hcl_string(git_tok)}"
    instance_type        = "{DEFAULT_INSTANCE}"
    odoo_conf_extra_b64  = "{conf_b64}"
{f'    repo_url            = "{_hcl_string(repo_url)}"\n' if repo_url else ""}{f'    repo_branch         = "{_hcl_string(repo_branch)}"\n' if repo_branch else ""}  }}
}}
''')

    header = ('# ----------------------------------------------------------------------\n'
              '# Auto-generated by deploy/_gen_presets.py from the profile store.\n'
              '# Do not edit by hand -- re-run deploy/12_publish_template.sh to refresh.\n'
              '# One preset per profile that has a built image + a successful mask run.\n'
              '# ----------------------------------------------------------------------\n\n')
    OUT.write_text(header + "\n".join(blocks))
    sys.stderr.write(f"generated {seen} preset(s) -> {OUT.relative_to(REPO)}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
