# Coder template: an odoo-synth developer environment.
#
# One EC2 instance (existing thin golden AMI + existing env instance profile) in
# a default-VPC subnet, NO public IP — the Coder agent dials OUT to the Coder
# server over the public internet; the developer reaches the workspace via
# Coder's Wireguard tunnel (web terminal / VS Code Web / port-forward / ssh),
# so the workspace needs zero inbound ports and no per-env SG rules. This is
# what deletes ~5 AWS artifacts per environment vs. the old hand-rolled design.
#
# The agent's startup_script is the existing Odoo boot logic (dump restore + ECR
# pull + addons bind-mount + admin reset) verbatim from user-data.sh.tmpl, with
# startup_script_behavior="blocking" so the workspace is not "ready" until Odoo
# answers HTTP. No nginx TLS sidecar (Coder proxies the web UI), no per-env
# Secrets Manager secret (the password is generated + stored as a Coder env var
# the agent reads), no EC2-tag readiness polling (Coder tracks agent lifecycle).

terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = ">= 2.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

data "coder_parameter" "instance_type" {
  name         = "instance_type"
  display_name = "EC2 instance type for the workspace."
  type         = "string"
  default      = "t3.large"
  order        = 0
}

data "coder_parameter" "ami_id" {
  name         = "ami_id"
  display_name = "Thin golden AMI (ubuntu + docker + code-server + awscli)."
  type         = "string"
  default      = ""
  order        = 1
}

data "coder_parameter" "instance_profile" {
  name         = "instance_profile"
  display_name = "Existing IAM instance profile (S3 dump read + ECR pull)."
  type         = "string"
  default      = ""
  order        = 2
}

data "coder_parameter" "subnet_id" {
  name         = "subnet_id"
  display_name = "Default-VPC subnet to launch in."
  type         = "string"
  default      = ""
  order        = 3
}

data "coder_parameter" "security_group_id" {
  name         = "security_group_id"
  display_name = "Existing env SG (egress only is sufficient; Coder tunnel carries access)."
  type         = "string"
  default      = ""
  order        = 4
}

data "coder_parameter" "region" {
  name         = "region"
  display_name = "AWS region."
  type         = "string"
  default      = "us-east-1"
  order        = 5
}

data "coder_parameter" "odoo_image" {
  name         = "odoo_image"
  display_name = "Provenance-baked Odoo ECR image to run against the masked DB."
  type         = "string"
  default      = ""
  order        = 6
}

data "coder_parameter" "dump_s3_uri" {
  name         = "dump_s3_uri"
  display_name = "s3://bucket/key of the masked pg_dump seeding the env's DB."
  type         = "string"
  default      = ""
  order        = 7
}

data "coder_parameter" "repo_url" {
  name         = "repo_url"
  display_name = "Addons repo cloned + live-mounted into Odoo."
  type         = "string"
  default      = ""
  order        = 8
}

data "coder_parameter" "repo_branch" {
  name         = "repo_branch"
  display_name = "Branch/tag/commit of the addons repo."
  type         = "string"
  default      = ""
  order        = 9
}

data "coder_parameter" "git_token_secret" {
  name         = "git_token_secret"
  display_name = "Secrets Manager secret id of a GitHub token (private addons clone)."
  type         = "string"
  default      = ""
  order        = 10
}

data "coder_parameter" "issue" {
  name         = "issue"
  display_name = "GitHub issue ref (provenance only)."
  type         = "string"
  default      = ""
  order        = 11
}

data "coder_parameter" "db_name" {
  name         = "db_name"
  display_name = "Local Postgres DB name seeded from the dump."
  type         = "string"
  default      = "odoo"
  order        = 12
}

data "coder_parameter" "odoo_master_password" {
  name         = "odoo_master_password"
  display_name = "Odoo database master password."
  type         = "string"
  default      = "change_me_master"
  order        = 13
}

data "coder_parameter" "odoo_conf_extra_b64" {
  name         = "odoo_conf_extra_b64"
  display_name = "Base64 of extra odoo.conf lines appended by the profile."
  type         = "string"
  default      = ""
  order        = 14
}

data "coder_parameter" "admin_password" {
  name         = "admin_password"
  display_name = "Per-workspace password (Odoo admin + code-server). Generated by the control panel."
  type         = "string"
  default      = "change-me"
  order        = 15
}

provider "aws" {
  region = data.coder_parameter.region.value
}

data "coder_workspace" "me" {}

# Per-workspace password generated by Coder and exposed to the agent as an env
# var — replaces the old per-env AWS Secrets Manager secret.
resource "coder_agent" "main" {
  os                     = "linux"
  arch                   = "amd64"
  startup_script_behavior = "blocking"
  startup_script = <<-EOT
    #!/usr/bin/env bash
    set -euo pipefail
    exec > >(tee -a /var/log/odoo-synth-env.log) 2>&1
    echo "[env ${data.coder_workspace.me.id}] boot $(date -u +%FT%TZ) issue=${data.coder_parameter.issue.value}"

    REGION="${data.coder_parameter.region.value}"
    if [ -z "$REGION" ]; then
      REGION="$(curl -s http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null || echo us-east-1)"
    fi
    DUMP_S3_URI="${data.coder_parameter.dump_s3_uri.value}"
    ODOO_IMAGE="${data.coder_parameter.odoo_image.value}"
    REPO_URL="${data.coder_parameter.repo_url.value}"
    REPO_BRANCH="${data.coder_parameter.repo_branch.value}"
    GIT_TOKEN_SECRET="${data.coder_parameter.git_token_secret.value}"
    DB_NAME="${data.coder_parameter.db_name.value}"
    ODOO_MASTER_PASSWORD="${data.coder_parameter.odoo_master_password.value}"
    ODOO_CONF_EXTRA_B64="${data.coder_parameter.odoo_conf_extra_b64.value}"
    ADMIN_PASS="${local.admin_password}"
    CODE_PASS="${local.admin_password}"
    WORKSPACE="/home/dev/workspace"
    REPO_DIR="$WORKSPACE/repo"
    PGPASS="odoo"
    NET="envnet"

    mkdir -p "$WORKSPACE"
    chown -R dev:dev /home/dev
    docker network create "$NET" >/dev/null 2>&1 || true

    # --- 1. local postgres holding the masked data ---
    docker rm -f env-db >/dev/null 2>&1 || true
    docker run -d --name env-db --network "$NET" \
      -e POSTGRES_PASSWORD="$PGPASS" -e POSTGRES_USER=odoo \
      -e POSTGRES_DB="$DB_NAME" -p 127.0.0.1:5432:5432 \
      -v /var/lib/env-db:/var/lib/postgresql/data postgres:16
    for _ in $(seq 1 60); do
      docker exec env-db pg_isready -U odoo -d "$DB_NAME" >/dev/null 2>&1 && break
      sleep 2
    done

    # --- 2. seed from the masked dump ---
    if [ -n "$DUMP_S3_URI" ]; then
      aws s3 cp "$DUMP_S3_URI" /tmp/masked.dump --region "$REGION"
      docker exec -i env-db pg_restore -U odoo -d "$DB_NAME" \
        --no-owner --no-privileges --clean --if-exists --disable-triggers \
        < /tmp/masked.dump || true
      rm -f /tmp/masked.dump
    fi

    # --- 3. GitHub token (private addons clone) ---
    GIT_TOKEN=""
    if [ -n "$GIT_TOKEN_SECRET" ]; then
      GIT_TOKEN="$(aws secretsmanager get-secret-value --secret-id "$GIT_TOKEN_SECRET" \
        --region "$REGION" --query SecretString --output text 2>/dev/null || echo '')"
    fi

    # --- 4. clone the addons repo ---
    if [ -n "$REPO_URL" ]; then
      CLONE_URL="$REPO_URL"
      if [ -n "$GIT_TOKEN" ]; then
        CLONE_URL="$(printf '%s' "$REPO_URL" | sed -E "s#https://#https://x-access-token:$GIT_TOKEN@#")"
      fi
      if sudo -u dev git clone "$CLONE_URL" "$REPO_DIR"; then
        if [ -n "$REPO_BRANCH" ]; then
          sudo -u dev git -C "$REPO_DIR" checkout "$REPO_BRANCH" 2>/dev/null \
            || { sudo -u dev git -C "$REPO_DIR" fetch --depth 1 origin "$REPO_BRANCH" \
                 && sudo -u dev git -C "$REPO_DIR" checkout FETCH_HEAD; } \
            || true
        fi
      fi
      if [ -n "$GIT_TOKEN" ] && [ -d "$REPO_DIR/.git" ]; then
        sudo -u dev git -C "$REPO_DIR" remote set-url origin "$REPO_URL" || true
      fi
    fi
    chown -R dev:dev /home/dev

    # --- 5. pull + run the provenance-baked odoo image ---
    if [ -n "$ODOO_IMAGE" ]; then
      REG="$${ODOO_IMAGE%%/*}"
      aws ecr get-login-password --region "$REGION" \
        | docker login --username AWS --password-stdin "$REG" || true
      docker pull "$ODOO_IMAGE" || true
      MOUNT_ARGS=""
      if [ -d "$REPO_DIR" ]; then
        ADDON_DIRS="$(cd "$REPO_DIR" && find . -maxdepth 3 -name __manifest__.py -printf '%h\n' 2>/dev/null \
          | sed 's#/[^/]*$##' | sed 's#^\./\{0,1\}##' | sort -u)"
        EXTRA=""
        if [ -n "$ADDON_DIRS" ]; then
          while IFS= read -r rel; do
            [ -z "$rel" ] && cpath="/mnt/live" || cpath="/mnt/live/$rel"
            EXTRA="$${EXTRA:+$EXTRA,}$cpath"
          done <<< "$ADDON_DIRS"
        else
          EXTRA="/mnt/live"
        fi
        MOUNT_ARGS="-v $${REPO_DIR}:/mnt/live:rw -e EXTRA_ADDONS_PATH=$EXTRA"
      fi
      docker rm -f env-odoo >/dev/null 2>&1 || true
      docker run -d --name env-odoo --network "$NET" \
        -p 127.0.0.1:18069:8069 \
        -e TARGET_DB_HOST=env-db -e TARGET_DB_PORT=5432 -e TARGET_DB_NAME="$DB_NAME" \
        -e TARGET_DB_USER=odoo -e TARGET_DB_PASSWORD="$PGPASS" \
        -e ODOO_MASTER_PASSWORD="$ODOO_MASTER_PASSWORD" \
        -e ODOO_CONF_EXTRA_B64="$ODOO_CONF_EXTRA_B64" \
        $MOUNT_ARGS "$ODOO_IMAGE" || true

      # install addons' python deps into the odoo container, then restart
      if [ -d "$REPO_DIR" ]; then
        DEPS="$(docker exec env-odoo python3 - <<'PY' 2>/dev/null || true
import ast, glob
MAP = {"dateutil":"python-dateutil","ldap":"python-ldap","Crypto":"pycryptodome",
       "jwt":"pyjwt","OpenSSL":"pyOpenSSL","PIL":"Pillow","yaml":"PyYAML",
       "bs4":"beautifulsoup4","magic":"python-magic","wand":"Wand"}
pkgs = set()
for m in glob.glob('/mnt/live/**/__manifest__.py', recursive=True):
    try: d = ast.literal_eval(open(m).read())
    except Exception: continue
    for p in ((d.get('external_dependencies') or {}).get('python') or []):
        pkgs.add(MAP.get(p, p))
print(' '.join(sorted(pkgs)))
PY
)"
        REQS="$(find "$REPO_DIR" -maxdepth 3 -name requirements.txt 2>/dev/null | head -5)"
        if [ -n "$DEPS" ] || [ -n "$REQS" ]; then
          REQ_ARGS=""
          for r in $REQS; do REQ_ARGS="$REQ_ARGS -r /mnt/live/$${r#$REPO_DIR/}"; done
          docker exec env-odoo pip install --no-cache-dir $DEPS $REQ_ARGS \
            >/home/dev/workspace/pip-addons.log 2>&1 || true
          chown dev:dev /home/dev/workspace/pip-addons.log 2>/dev/null || true
          docker restart env-odoo >/dev/null 2>&1 || true
        fi
      fi

      # restore a usable admin login (masked DB has no passwords)
      if [ -n "$ADMIN_PASS" ]; then
        for _ in $(seq 1 30); do
          docker exec env-db pg_isready -U odoo -d "$DB_NAME" >/dev/null 2>&1 && break
          sleep 2
        done
        ADMIN_HASH="$(docker exec env-odoo python3 -c \
          "from passlib.context import CryptContext; print(CryptContext(['pbkdf2_sha512']).hash('$ADMIN_PASS'))" \
          2>/dev/null || echo '')"
        if [ -n "$ADMIN_HASH" ]; then
          docker exec env-db psql -U odoo -d "$DB_NAME" -c \
            "UPDATE res_users SET login='admin', password='$ADMIN_HASH', active=true WHERE id=2;" \
            >/dev/null 2>&1 || true
        fi
      fi
    fi

    # --- 6. code-server (browser VS Code), passwordless inside the tunnel ---
    install -d -o dev -g dev /home/dev/.config/code-server
    cat > /home/dev/.config/code-server/config.yaml <<CS
bind-addr: 127.0.0.1:8443
auth: password
password: $CODE_PASS
cert: false
CS
    chown dev:dev /home/dev/.config/code-server/config.yaml
    chmod 600 /home/dev/.config/code-server/config.yaml
    cat > /etc/systemd/system/code-server.service <<CSUNIT
[Unit]
Description=code-server (odoo-synth env)
After=network-online.target docker.service
Wants=network-online.target
[Service]
Type=simple
User=dev
Environment=HOME=/home/dev
ExecStart=/usr/bin/code-server /home/dev/workspace
Restart=always
[Install]
WantedBy=multi-user.target
CSUNIT
    systemctl daemon-reload
    systemctl enable --now code-server

    # --- 7. port-forwards Coder opens so the dev reaches odoo + code-server ---
    # `coder_port` resources below tell Coder to proxy these through the tunnel.

    # --- 8. readiness: block startup until Odoo answers HTTP ---
    if [ -n "$ODOO_IMAGE" ]; then
      for _ in $(seq 1 72); do
        code="$(curl -s -o /dev/null -w '%%{http_code}' --max-time 5 http://127.0.0.1:18069/web/login 2>/dev/null || echo 000)"
        case "$code" in 200|301|302|303) echo "[env] odoo ready (http $code)"; exit 0 ;; esac
        sleep 10
      done
      echo "[env] WARN: odoo did not answer within 12m; marking ready anyway"
    fi
  EOT
  env = {
    # expose the per-workspace password to the agent so the startup_script can
    # read it as $CODER_ENV_ADMIN_PASSWORD, and to the Coder API so the panel
    # can surface it in the /password endpoint.
    CODER_ENV_ADMIN_PASSWORD = local.admin_password
    CODER_ENV_CODE_PASSWORD  = local.admin_password
  }
}

locals {
  # one password per workspace, for both Odoo admin and code-server (matches the
  # old design where both shared the per-env secret). Set by the control panel as
  # a template parameter so it knows the value for the /password endpoint.
  admin_password = data.coder_parameter.admin_password.value
}



# workspace VM: existing AMI + profile + subnet, no public IP, no per-env SG.
resource "aws_instance" "workspace" {
  ami                  = data.coder_parameter.ami_id.value
  instance_type        = data.coder_parameter.instance_type.value
  subnet_id            = data.coder_parameter.subnet_id.value
  vpc_security_group_ids = [data.coder_parameter.security_group_id.value]
  iam_instance_profile  = data.coder_parameter.instance_profile.value
  associate_public_ip_address = true
  # cloud-init runs the Coder agent bootstrap. We inline the script (rather than
  # using coder_agent.main.init_script) so we can inject CODER_AGENT_TOKEN -- the
  # default init_script sets CODER_AGENT_AUTH=token but not the token itself, which
  # the agent requires to authenticate. The agent's startup_script (Odoo boot) runs
  # after the agent connects to the server.
  user_data = <<-EOT
    #!/usr/bin/env sh
    set -eux
    export CODER_AGENT_TOKEN="${coder_agent.main.token}"
    export CODER_AGENT_URL="${data.coder_workspace.me.access_url}"
    export CODER_AGENT_AUTH=token
    B="$(mktemp -d -t coder.XXXXXX)"; cd "$B"
    curl -fsSL --compressed "$${CODER_AGENT_URL}/bin/coder-linux-amd64" -o coder || \
      wget -q "$${CODER_AGENT_URL}/bin/coder-linux-amd64" -O coder
    chmod +x coder
    exec ./coder agent
  EOT
  user_data_replace_on_change = true
  tags = {
    Name              = "odoo-synth-env-${data.coder_workspace.me.name}"
    "odoo-synth:env"    = data.coder_workspace.me.id
    "odoo-synth:managed" = "true"
    "odoo-synth:issue"  = data.coder_parameter.issue.value
  }
}

# start/stop the instance with the workspace (Coder auto-stop).
resource "aws_ec2_instance_state" "workspace" {
  instance_id = aws_instance.workspace.id
  state       = data.coder_workspace.me.transition == "start" ? "running" : "stopped"
}

# port-forwards through the Coder tunnel so the dev reaches odoo + code-server
# without any inbound SG rule or public IP.
resource "coder_app" "odoo" {
  agent_id     = coder_agent.main.id
  slug         = "odoo"
  display_name = "Odoo (masked)"
  icon         = "/icon/odoo.svg"
  url          = "http://localhost:18069"
  healthcheck {
    url       = "http://localhost:18069/web/login"
    interval  = 10
    threshold = 3
  }
}

resource "coder_app" "vscode" {
  agent_id     = coder_agent.main.id
  slug         = "vscode"
  display_name = "VS Code (code-server)"
  icon         = "/icon/vscode.svg"
  url          = "http://localhost:8443"
  healthcheck {
    url       = "http://localhost:8443/healthz"
    interval  = 5
    threshold = 3
  }
}
